// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKubeConfigDialog() {
  return window['go']['main']['App']['AddKubeConfigDialog']();
}

export function DeleteResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteResource'](arg1, arg2, arg3, arg4, arg5);
}

export function DiscoverResources() {
  return window['go']['main']['App']['DiscoverResources']();
}

export function GetResourceYAML(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetResourceYAML'](arg1, arg2, arg3, arg4, arg5);
}

export function InitialContext() {
  return window['go']['main']['App']['InitialContext']();
}

export function ListContexts() {
  return window['go']['main']['App']['ListContexts']();
}

export function ListKubeConfigs() {
  return window['go']['main']['App']['ListKubeConfigs']();
}

export function ListNamespaces() {
  return window['go']['main']['App']['ListNamespaces']();
}

export function ListResourceTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListResourceTable'](arg1, arg2, arg3, arg4);
}

export function RemoveKubeConfig(arg1) {
  return window['go']['main']['App']['RemoveKubeConfig'](arg1);
}

export function UseContext(arg1) {
  return window['go']['main']['App']['UseContext'](arg1);
}
