// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddKubeConfigDialog():Promise<string>;

export function AnnotateResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function DeleteResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DiscoverResources():Promise<Array<main.APIResource>>;

export function FluxReconcile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function FluxReconcileWithSource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function FluxStatus():Promise<Array<main.FluxKindStatus>>;

export function GetEventsFor(arg1:string,arg2:string,arg3:string):Promise<Array<main.EventInfo>>;

export function GetResourceJSON(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function GetResourceUISettings(arg1:string):Promise<main.ResourceUISettings>;

export function GetResourceYAML(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function InitialContext():Promise<string>;

export function ListContexts():Promise<Array<main.ContextInfo>>;

export function ListKubeConfigs():Promise<Array<main.KubeConfigInfo>>;

export function ListNamespaces():Promise<Array<string>>;

export function ListResourceTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.TableResult>;

export function PatchResource(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function RemoveKubeConfig(arg1:string):Promise<void>;

export function ResourceHasItems(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;

export function SetHideEmptyCRDs(arg1:boolean):Promise<main.ResourceUISettings>;

export function SetResourceFavorite(arg1:string,arg2:string,arg3:boolean):Promise<main.ResourceUISettings>;

export function SetSectionCollapsed(arg1:string,arg2:string,arg3:boolean):Promise<main.ResourceUISettings>;

export function SetSuspend(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function UseContext(arg1:string):Promise<void>;
